version: '3.5'

services:
  vaultwarden:
    image: vaultwarden/server:latest #swap tag to raspberry to run on a raspberry pi
    container_name: vaultwarden
    expose:
      - "80"
      - "3012"
    volumes:
      - ${ROOT_PATH}/Data/Vaultwarden:/data
    restart: on-failure
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
#      ADMIN_TOKEN: ${ADMIN_TOKEN}
    networks:
      - "vaultwarden"
 
  nginx:
    build: './Docker/nginx'
    container_name: nginx
    links:
      - "vaultwarden"
      - "vw_backup"
    environment:
      NGINX_PORT: "${NGINX_PORT}"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
    command: /bin/sh -c "/run_nginx.sh"
    restart: on-failure
    networks:
      - "vaultwarden"
      - "nginx-proxy"

  vw_backup:
    image: bruceforce/bw_backup:latest #swap tag to rpi3 to run on a raspberry pi
    container_name: vw_backup
    restart: on-failure
    depends_on:
      - vaultwarden
    volumes:
      - ${ROOT_PATH}/Data/Vaultwarden:/data
      - ${ROOT_PATH}/Data/Vaultwarden-Backup:/backup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_FILE=/data/db.sqlite3
      - BACKUP_FILE=/backup/backup.sqlite3
      - BACKUP_FILE_PERMISSIONS=700
      - CRON_TIME=0 1 * * *
      - TIMESTAMP=false
      - UID=0
      - GID=0

networks:
  nginx-proxy:
    external: true
    name: "nginx-proxy"
  vaultwarden:
    driver: bridge